stages:
  pdf_to_text:
    cmd: python src/spaceapps2022/pdf_to_text.py data/01_raw/ data/03_primary/texts
    deps:
      - data/01_raw/
      - src/spaceapps2022/pdf_to_text.py
    outs:
      - data/03_primary/texts
    
  text_to_parquet:
    cmd: python src/spaceapps2022/text_to_parquet.py data/03_primary/texts data/04_feature/text.parquet
    deps:
      - data/03_primary/texts
      - src/spaceapps2022/text_to_parquet.py
    outs:
      - data/04_feature/text.parquet
    
  parquet_to_embeddings:
    cmd: python src/spaceapps2022/parquet_to_embeddings.py data/04_feature/text.parquet data/05_model_input/embeddings.npy
    deps:
      - data/04_feature/text.parquet
      - src/spaceapps2022/parquet_to_embeddings.py
    outs:
      - data/05_model_input/embeddings.npy