vars:
  - limit: 1000


stages:
  get_data:
    cmd: python src/spaceapps2022/get_sti_data.py data/02_intermediate/data.csv ${limit}
    deps:
      - src/spaceapps2022/get_sti_data.py
      - data/01_raw/ntrs-public-metadata.json
    outs:
      - data/02_intermediate/data.csv


  get_files:
    cmd: python src/spaceapps2022/get_sti_files.py data/02_intermediate/data.csv data/01_raw
    deps:
      - src/spaceapps2022/get_sti_data.py
      - data/02_intermediate/data.csv
    outs:
      - data/01_raw/texts
      - data/01_raw/pdfs


  # pdf_to_text:
  #   cmd: python src/spaceapps2022/pdf_to_text.py data/01_raw/pdfs data/03_primary/texts
  #   deps:
  #     - data/01_raw/pdfs
  #     - src/spaceapps2022/pdf_to_text.py
  #   outs:
  #     - data/03_primary/texts
  #     - data/03_primary/images
    
  meta_to_abstracts:
    cmd: python src/spaceapps2022/meta_to_abstracts.py data/01_raw/ntrs-public-metadata.json data/04_feature/abstracts.parquet
    deps:
      # - data/03_primary/texts
      - data/01_raw/ntrs-public-metadata.json
      - src/spaceapps2022/meta_to_abstracts.py
    outs:
      - data/04_feature/abstracts.parquet

  text_to_parquet:
    cmd: python src/spaceapps2022/text_to_parquet.py data/01_raw/texts data/04_feature/text.parquet
    deps:
      # - data/03_primary/texts
      - data/01_raw/texts
      - src/spaceapps2022/text_to_parquet.py
    outs:
      - data/04_feature/text.parquet

    
  parquet_to_embeddings:
    cmd: python src/spaceapps2022/parquet_to_embeddings.py data/04_feature/text.parquet data/05_model_input/embeddings.npy
    deps:
      - data/04_feature/text.parquet
      - src/spaceapps2022/parquet_to_embeddings.py
    outs:
      - data/05_model_input/embeddings.npy


  abstracts_to_embeddings:
    cmd: python src/spaceapps2022/abstracts_to_embeddings.py data/04_feature/abstracts.parquet data/05_model_input/abstract_embeddings.npy
    deps:
      - data/04_feature/abstracts.parquet
      - src/spaceapps2022/abstracts_to_embeddings.py
    outs:
      - data/05_model_input/abstract_embeddings.npy

  parquet_to_topics:
    cmd: python src/spaceapps2022/parquet_to_topics.py data/04_feature/text.parquet
    deps:
      - data/04_feature/text.parquet
      - src/spaceapps2022/parquet_to_topics.py
